# Specify the base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the project files to the working directory
COPY . .

# Install project dependencies
RUN pip install -r requirements.txt

# Set the entry point command
CMD [ "python", "main.py" ]
